export const ADD_ADDON = 'ADD_ADDON';
export const REMOVE_ADDON = 'REMOVE_ADDON';
export const SET_ADDONS = 'SET_ADDONS';
export const FETCH_ADDONS_FAILED = 'FETCH_ADDONS_FAILED';

export const POST_ORDER = 'POST_ORDER';
export const ORDER_FAILED = 'ORDER_FAILED';
export const ORDER_START = 'ORDER_START';
export const ORDER_INIT = 'ORDER_INIT';

export const FETCH_ORDERS_INIT = 'FETCH_ORDERS_INIT';
export const FETCH_ORDERS = 'FETCH_ORDERS';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAILED = 'FETCH_ORDERS_FAIL';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILED = 'AUTH_FAILED';
